import type { Metadata, Viewport } from 'next'
import { Inter } from 'next/font/google'
import { GeistMono } from 'geist/font/mono'
import Link from 'next/link'
import { Analytics } from '@vercel/analytics/next'
import { SITE_URL } from '@/lib/site'
import { AuthButton } from '@/components/AuthButton'
import { AdminNav } from '@/components/AdminNav'
import { FavoritesProvider } from '@/components/FavoritesProvider'
import { Logo } from '@/components/brand/Logo'
import { EmailCapture } from '@/components/EmailCapture'
import { MobileTabBar } from '@/components/MobileTabBar'
import { NavLink } from '@/components/NavLink'
import { RouteTransition } from '@/components/RouteTransition'
import './globals.css'

// Inter — the brand face. Drives the wordmark, headlines, and body so the
// whole UI shares one type voice. (Geist Mono stays for code / eyebrow labels.)
const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--ff-inter',
  display: 'swap',
})

const siteUrl = SITE_URL

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: 'Skill Me · The App Store for Claude Skills',
    template: '%s · Skill Me',
  },
  description:
    'Install intelligence. Browse curated Claude skills and install them from inside Claude. No setup, no ZIP files, no copy-pasting. An independent, community project — not affiliated with or endorsed by Anthropic.',
  openGraph: {
    title: 'Skill Me · The App Store for Claude Skills',
    description: 'Install intelligence. Connect once, install anything.',
    url: siteUrl,
    siteName: 'Skill Me',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Skill Me · The App Store for Claude Skills',
    description: 'Install intelligence. Connect once, install anything.',
    creator: '@aouellets',
  },
  // Icons are auto-generated by Next from app/icon.svg and app/apple-icon.tsx —
  // no manual <link> tags, no stale favicon.ico reference.
}

export const viewport: Viewport = {
  themeColor: '#1c1a17', // brand ink
  width: 'device-width',
  initialScale: 1,
}

async function Header() {
  return (
    <header className="sticky top-0 z-40 border-b border-shelf-border/80 bg-shelf-void/70 backdrop-blur-xl supports-[backdrop-filter]:bg-shelf-void/55">
      <div className="mx-auto flex h-16 max-w-content items-center justify-between px-4 sm:px-6 lg:px-8">
        <Link
          href="/"
          aria-label="Skill Me home"
          className="shrink-0 transition-opacity hover:opacity-80"
        >
          <Logo />
        </Link>
        {/* Browse / Packs / Connect live in the bottom tab bar on mobile, so the
            mobile header stays calm (wordmark + account). They reappear here at
            lg+, where the bottom bar is hidden — desktop nav is unchanged. */}
        <nav className="flex min-w-0 items-center gap-0.5 sm:gap-2">
          <NavLink
            href="/browse"
            className="hidden rounded-sm px-2.5 py-2 text-sm text-shelf-text-secondary transition-colors hover:text-shelf-text-primary sm:px-3 lg:inline-flex"
          >
            Browse
          </NavLink>
          <NavLink
            href="/packs"
            className="hidden rounded-sm px-2.5 py-2 text-sm text-shelf-text-secondary transition-colors hover:text-shelf-text-primary sm:px-3 lg:inline-flex"
          >
            Packs
          </NavLink>
          <AdminNav />
          <AuthButton />
          <Link href="/connect" className="btn btn-primary ml-1 hidden lg:inline-flex">
            <span className="sm:hidden">Connect</span>
            <span className="hidden sm:inline">Connect to Claude</span>
          </Link>
        </nav>
      </div>
    </header>
  )
}

function Footer() {
  return (
    <footer className="mt-16 border-t border-shelf-border sm:mt-28">
      {/* Extra bottom padding on mobile clears the fixed bottom tab bar (plus the
          home-indicator safe area); desktop has no bar, so it resets at lg. */}
      <div className="mx-auto max-w-content px-4 pt-12 pb-[calc(5rem+env(safe-area-inset-bottom))] sm:px-6 lg:px-8 lg:pb-12">
        <div className="flex flex-col gap-8 sm:flex-row sm:items-start sm:justify-between">
          <div className="max-w-xs">
            <Logo />
            <p className="mt-3 text-sm leading-relaxed text-shelf-text-tertiary">
              The App Store for Claude skills. Connect once, install anything.
            </p>
            <div className="mt-5">
              <EmailCapture placement="footer" label="New skills weekly" />
            </div>
          </div>
          <div className="grid grid-cols-2 gap-x-12 gap-y-2 text-sm sm:grid-cols-2">
            <span className="col-span-2 mb-1 font-mono text-xs uppercase tracking-widest text-shelf-text-tertiary">
              Explore
            </span>
            <Link href="/browse" className="text-shelf-text-secondary transition-colors hover:text-shelf-text-primary">
              Browse skills
            </Link>
            <Link href="/packs" className="text-shelf-text-secondary transition-colors hover:text-shelf-text-primary">
              Skill packs
            </Link>
            <Link href="/connect" className="text-shelf-text-secondary transition-colors hover:text-shelf-text-primary">
              Connect to Claude
            </Link>
            <Link href="/about" className="text-shelf-text-secondary transition-colors hover:text-shelf-text-primary">
              About
            </Link>
            <Link href="/submit" className="text-shelf-text-secondary transition-colors hover:text-shelf-text-primary">
              Submit a skill
            </Link>
            <Link href="/skill-media-guide" className="text-shelf-text-secondary transition-colors hover:text-shelf-text-primary">
              Media guide
            </Link>
            <Link href="/privacy" className="text-shelf-text-secondary transition-colors hover:text-shelf-text-primary">
              Privacy
            </Link>
            <a
              href="https://github.com/aouellets/skillme"
              target="_blank"
              rel="noopener noreferrer"
              className="text-shelf-text-secondary transition-colors hover:text-shelf-text-primary"
            >
              GitHub
            </a>
            <a
              href="https://x.com/aouellets"
              target="_blank"
              rel="noopener noreferrer"
              className="text-shelf-text-secondary transition-colors hover:text-shelf-text-primary"
            >
              X / Twitter
            </a>
          </div>
        </div>
        <div className="rule mt-10" />
        <p className="mt-6 text-xs text-shelf-text-tertiary">
          © {new Date().getFullYear()} Skill Me. Built for the Claude community.
        </p>
        <p className="mt-2 max-w-2xl text-xs leading-relaxed text-shelf-text-tertiary">
          Skill Me is an independent, community-built project. It is not
          affiliated with, endorsed by, or sponsored by Anthropic. &ldquo;Claude&rdquo;
          is a trademark of Anthropic.
        </p>
      </div>
    </footer>
  )
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${GeistMono.variable}`}
    >
      <body>
        {/* Page-wide ambient aura — a soft, constant warm field behind every
            page. Fixed + pinned behind content in globals.css (.aura-field). */}
        <div className="aura-field" aria-hidden />
        <FavoritesProvider>
          <div className="flex min-h-dvh flex-col">
            <Header />
            <main className="flex-1">
              <RouteTransition>{children}</RouteTransition>
            </main>
            <Footer />
          </div>
          <MobileTabBar />
        </FavoritesProvider>
        <Analytics />
      </body>
    </html>
  )
}
