import type { PackCategory } from './types'

/**
 * Canonical pack catalog — the single source of truth shared by the database
 * seeder (`scripts/seed-packs.ts`) and the app's offline fallback
 * (`SEED_PACKS` in `lib/packs.ts`). Keeping one list here prevents the two from
 * drifting (and the per-pack skill count from going stale).
 *
 * Every entry in `skill_slugs` must be a real skill slug from
 * `lib/seed-data.ts`; the seeder warns on any that don't resolve.
 *
 * This module is intentionally free of `server-only` and runtime dependencies so
 * the tsx-run seed script can import it directly.
 */
export interface PackDefinition {
  slug: string
  name: string
  tagline: string
  description: string
  author: string
  category: PackCategory
  tags: string[]
  featured: boolean
  verified: boolean
  free: boolean
  install_count: number
  repo_url?: string             // GitHub repo for this pack (starrable)
  skill_slugs: string[]
}

export const PACK_DEFINITIONS: PackDefinition[] = [
  // ── Launch packs ────────────────────────────────────────────────────────
  {
    slug: 'solo-founder-stack',
    name: 'Solo Founder Stack',
    tagline: "For solo founders: go from idea to first paying customers without a team.",
    description:
      "When you are building alone and need to find a market, price it, launch it, and close the first customers yourself. Use this when you have a product idea or early MVP and your next milestone is revenue — it sizes the opportunity, pins down pricing, sequences the launch, and writes the landing page and cold outreach that convert.",
    author: 'Skill Me',
    category: 'business',
    tags: ['startups', 'founder', 'business'],
    featured: true,
    verified: true,
    free: true,
    install_count: 14800,
    skill_slugs: ["market-sizing", "competitive-intelligence", "pricing-strategy", "unit-economics", "go-to-market-planner", "landing-page-copy", "cold-email-craft"],
  },
  {
    slug: 'design-system-builder',
    name: 'Design System Builder',
    tagline: "For design/UI engineers: ship a production design system, tokens to handoff.",
    description:
      "Reach for this when you're standing up or maturing a real design system and need every layer to fit together — not a pile of one-off design tips. You get a coherent token architecture (global → semantic → component) with theming and dark mode, accessible color and contrast, a consistent icon and motion system, clean component APIs, and implementation-ready specs your engineers can build from. The result is a system that stays consistent across light/dark, scales past the first few screens, and survives the handoff to engineering.",
    author: 'Skill Me',
    category: 'design',
    tags: ['design-system', 'design', 'components'],
    featured: true,
    verified: true,
    free: true,
    install_count: 9200,
    skill_slugs: [
      'design-token-system', 'component-api-design', 'color-accessibility',
      'dark-mode-design', 'icon-system', 'prototype-spec',
      'animation-system', 'anthropic-frontend-design',
    ],
  },
  {
    slug: 'content-marketing-engine',
    name: 'Content Marketing Engine',
    tagline: "For marketers: plan, write, and keep on-brand content flowing across every channel.",
    description:
      "Reach for this when you own a content calendar and need to ship across channels without losing your voice. It runs the full loop: brief and plan a piece, draft it as a LinkedIn post, tweet thread, technical blog, newsletter, landing page, or case study, and keep every output on-brand. The outcome is a repeatable engine that turns one idea into channel-ready content instead of starting from a blank page.",
    author: 'Skill Me',
    category: 'writing',
    tags: ['content', 'marketing', 'writing'],
    featured: true,
    verified: true,
    free: true,
    install_count: 22400,
    skill_slugs: [
      'linkedin-post-writer', 'tweet-thread-builder', 'technical-blog-engine',
      'email-newsletter-pro', 'landing-page-copy', 'case-study-builder',
      'brand-guidelines', 'content-brief',
    ],
  },
  {
    slug: 'engineering-workflow',
    name: 'Engineering Workflow',
    tagline: "For engineers using Claude: from test-first code to review, clean commit, PR & release.",
    description:
      "Reach for this when you want the craft around a change to stay disciplined instead of rushed. It runs the whole arc: write code test-first and keep the types honestly strict, self-review the diff systematically, then turn it into a clean conventional commit, a reviewer-ready PR description, and the changelog and README updates a release needs — so the parts engineers get judged on come out consistent rather than improvised at the end.",
    author: 'Skill Me',
    category: 'coding',
    tags: ['git', 'workflow', 'engineering'],
    featured: true,
    verified: true,
    free: true,
    install_count: 31600,
    skill_slugs: [
      'git-commit-writer', 'pr-description-writer', 'changelog-generator',
      'readme-generator', 'code-review-checklist', 'typescript-strict',
      'tdd-expert', 'karpathy-behavioral-rules',
    ],
  },
  {
    slug: 'legal-team-starter',
    name: 'Legal Team Starter',
    tagline: "Founders doing their own legal: draft ToS, flag risky contract clauses, map compliance.",
    description:
      "Reach for this when you are a founder or lean in-house team handling legal work without a firm on retainer. It gets you to a solid first draft of your SaaS terms of service and privacy policy, flags the non-standard clauses (non-competes, IP assignment, severance) hiding in an employment agreement before you sign, maps which regulations apply to your product and where the gaps are, and verifies factual claims against independent sources when you need to be sure. The legal skills are explicit that they produce strong drafts and triage, not legal advice — use them to know what to fix and when to bring in a lawyer.",
    author: 'Skill Me',
    category: 'business',
    tags: ['legal', 'compliance', 'contracts'],
    featured: false,
    verified: true,
    free: true,
    install_count: 7400,
    skill_slugs: ["regulatory-scan", "terms-of-service", "employment-contract"],
  },
  {
    slug: 'data-analyst-toolkit',
    name: 'Data Analyst Toolkit',
    tagline: "For data analysts: turn raw data into board-ready findings, from query to the so-what.",
    description:
      "Reach for this when you have data and need a defensible answer leadership will act on. Pull insights out of SQL and pandas, run the analysis (A/B tests, funnels, cohorts/LTV/churn), then package it as a clear narrative with the headline finding and the so-what — the full path from query to board-ready story.",
    author: 'Skill Me',
    category: 'data',
    tags: ['analytics', 'data', 'sql'],
    featured: false,
    verified: true,
    free: true,
    install_count: 18200,
    skill_slugs: [
      'sql-to-insights', 'pandas-expert', 'ab-test-analyzer',
      'funnel-analysis', 'customer-analytics', 'data-story',
      'revenue-modeling',
    ],
  },
  {
    slug: 'saas-growth-stack',
    name: 'SaaS Growth Stack',
    tagline: "For SaaS founders & growth leads: model, monetize, and retain — close funnel leaks.",
    description:
      "Reach for this when you're past product-market fit and need to turn a working SaaS into a compounding revenue machine — not chase one-off tactics. It hands you a growth model to see where the funnel leaks, product analytics to instrument and find them, churn-reduction to plug retention, and a pricing + unit-economics + expansion layer to make every retained account worth more. Pull it out for board-prep, a growth-strategy reset, or when CAC payback and churn are fighting your roadmap.",
    author: 'Skill Me',
    category: 'business',
    tags: ['saas', 'growth', 'product'],
    featured: false,
    verified: true,
    free: true,
    install_count: 16400,
    skill_slugs: [
      'growth-model', 'churn-reduction', 'expansion-revenue',
      'customer-success-qbr', 'product-analytics', 'unit-economics',
      'saas-pricing',
    ],
  },
  {
    slug: 'remote-team-toolkit',
    name: 'Remote Team Toolkit',
    tagline: "For remote managers: keep the team aligned async, without back-to-back meetings.",
    description:
      "Reach for this when your remote team is drowning in status meetings and threads. It turns meetings into tracked actions, writes the async updates and stakeholder notes that replace standups, structures 1:1s, and helps you deliver feedback that lands — so alignment happens in writing, on everyone's own clock, and your calendar opens back up.",
    author: 'Skill Me',
    category: 'productivity',
    tags: ['remote', 'teams', 'management'],
    featured: false,
    verified: true,
    free: true,
    install_count: 12800,
    skill_slugs: [
      'meeting-notes-to-actions', 'weekly-review', 'okr-builder',
      'feedback-writer', 'stakeholder-update', 'async-communication',
      '1on1-agenda',
    ],
  },
  {
    slug: 'devops-platform-engineer',
    name: 'DevOps & Platform Engineering',
    tagline: "For platform engineers: provision, ship, and observe production infra with confidence.",
    description:
      "Reach for this when you own the infrastructure behind a service and need it to ship and stay up. It takes you from provisioning cloud resources as code, through CI/CD pipelines and containerization, to running workloads on Kubernetes and seeing inside them in production. The result: a repeatable, observable platform you can hand to a team instead of a pile of one-off scripts.",
    author: 'Skill Me',
    category: 'coding',
    tags: ['devops', 'infrastructure', 'platform'],
    featured: false,
    verified: true,
    free: true,
    install_count: 19400,
    skill_slugs: [
      'terraform-expert', 'github-actions', 'docker-compose-wizard',
      'kubernetes-basics', 'observability-stack', 'env-doctor',
      'security-audit',
    ],
  },
  {
    slug: 'academic-researcher',
    name: 'Academic Researcher',
    tagline: "For researchers: go from scattered papers to a synthesized, citation-clean academic draft.",
    description:
      "For grad students, academics, and research analysts who need defensible writing, not just notes. Reach for this when you have a pile of papers and a deadline: run a formal PRISMA review or a narrative synthesis, pin down themes and gaps, verify every claim and citation, then ship a thesis-driven essay or brief that survives peer review. The full path from literature to a draft you can defend.",
    author: 'Skill Me',
    category: 'research',
    tags: ['academic', 'research', 'writing'],
    featured: false,
    verified: true,
    free: true,
    install_count: 8600,
    skill_slugs: [
      'systematic-review', 'literature-review', 'citation-tracker',
      'academic-essay', 'policy-brief', 'fact-checker',
    ],
  },

  // ── Expansion packs ─────────────────────────────────────────────────────
  {
    slug: 'personal-operating-system',
    name: 'Personal Operating System',
    tagline: "For high-performers who want their habits, focus, and health running on autopilot.",
    description:
      "Stop white-knuckling your way through the day. Install the operating system high-performers run on: habits that stick without willpower, deep-focus blocks that protect your best hours, sleep and stress under control, and a second brain that remembers so you don't have to. Reach for this when your routines have drifted and you want one coherent system instead of a dozen disconnected hacks.",
    author: 'Skill Me',
    category: 'personal',
    tags: ['personal', 'habits', 'productivity'],
    featured: true,
    verified: true,
    free: true,
    install_count: 13400,
    skill_slugs: [
      'habit-builder', 'sleep-optimizer', 'study-system',
      'journal-framework', 'decision-making', 'stress-management',
      'goals-accountability', 'second-brain', 'deep-work-planner',
    ],
  },
  {
    slug: 'ai-engineer-toolkit',
    name: 'AI Engineer Toolkit',
    tagline: "When an AI feature has to survive production, not just demo: prompts, evals, agents, MCP.",
    description:
      "Reach for this when you're putting an AI feature into production, not just prototyping one. It carries you through the real build loop: write prompts that hold up under edge cases, prove they work with rigorous evals before you ship, orchestrate multi-step agents when one call isn't enough, and expose your own tools as MCP servers Claude can call. It also covers the surrounding engineering work — deep multi-source research, sound ML feature design, and recoverable, observable error handling — so the system holds together end to end. The outcome is an AI feature you can defend in code review and trust in front of users.",
    author: 'Skill Me',
    category: 'coding',
    tags: ['ai', 'llm', 'agents'],
    featured: true,
    verified: true,
    free: true,
    install_count: 24600,
    skill_slugs: [
      'prompt-engineer', 'mcp-builder', 'llm-evaluation',
      'agent-orchestration', 'deep-research', 'ml-feature-engineering',
      'error-handling',
    ],
  },
  {
    slug: 'product-manager-stack',
    name: 'Product Manager Stack',
    tagline: "For PMs: turn strategy into roadmaps, specs, sprints, and the metrics to prove it shipped.",
    description:
      "Reach for this when you own a product line and need to move from strategy to shipped, measurable outcomes without switching tools for every artifact. It carries you across the full PM loop: set OKRs, build a roadmap leadership trusts, ground decisions in personas and user flows, hand engineering crisp specs and tickets, run the sprint, then read the analytics to see if it worked. The result is a product org aligned on outcomes instead of a feature list — and a paper trail that survives the next reorg.",
    author: 'Skill Me',
    category: 'productivity',
    tags: ['product', 'pm', 'roadmap'],
    featured: false,
    verified: true,
    free: true,
    install_count: 17200,
    skill_slugs: [
      'product-roadmap', 'technical-spec', 'user-persona',
      'sprint-planning', 'okr-builder', 'product-analytics',
      'user-flow-mapper', 'jira-ticket-writer',
    ],
  },
  {
    slug: 'full-stack-web-dev',
    name: 'Full-Stack Web Dev',
    tagline: "For devs shipping a Next.js + Postgres app: auth, billing, and a fast launch end to end.",
    description:
      "Reach for this when you're building a real Next.js + Supabase/Postgres product and need it production-ready, not just running locally. It carries you from data model and API to OAuth login, Stripe subscriptions, and a fast, Core-Web-Vitals-clean launch — so the full path from schema to shipped feature is covered by one coherent stack instead of stitched-together advice.",
    author: 'Skill Me',
    category: 'coding',
    tags: ['web', 'fullstack', 'nextjs'],
    featured: false,
    verified: true,
    free: true,
    install_count: 26800,
    skill_slugs: [
      'nextjs-app-router', 'graphql-schema', 'database-schema',
      'oauth-flow', 'stripe-integration', 'supabase-expert',
      'web-performance', 'api-design',
    ],
  },
  {
    slug: 'job-search-kit',
    name: 'Job Search Kit',
    tagline: "For job seekers: tailored applications to a signed offer, plus outreach and negotiation.",
    description:
      "Reach for this when you are actively job hunting and want every stage to pull in the same direction. Land more first conversations with applications tuned to the role and outreach that earns replies, turn a thin network into a steady stream of warm intros, and walk into the offer talk with the anchoring and BATNA prep to capture what you are worth. One kit for the whole search, from first application to signed offer.",
    author: 'Skill Me',
    category: 'personal',
    tags: ['career', 'job-search', 'personal'],
    featured: false,
    verified: true,
    free: true,
    install_count: 15600,
    skill_slugs: [
      'job-application', 'salary-negotiation', 'networking-system',
      'linkedin-post-writer', 'cold-email-craft',
    ],
  },
  {
    slug: 'fiction-writers-room',
    name: "Fiction Writer's Room",
    tagline: "For fiction writers: plot the arc, draft vivid scenes, hold the voice, then revise.",
    description:
      "Reach for this when you're writing long-form fiction and want every stage to hold together — not a pile of disconnected drafting tips. Architect the plot and beat structure, draft scenes thick with sensory detail and subtext, keep one consistent narrative voice across the whole manuscript, then run a developmental-and-line revision pass that tightens prose and catches continuity and POV slips. It carries a single story from outline to revised draft.",
    author: 'Skill Me',
    category: 'writing',
    tags: ['fiction', 'writing', 'storytelling'],
    featured: false,
    verified: true,
    free: true,
    install_count: 9100,
    skill_slugs: ["story-structure-architect", "fiction-scene-writer", "ghostwriter", "manuscript-reviser"],
  },
  {
    slug: 'data-engineering-pipeline',
    name: 'Data Engineering Pipeline',
    tagline: "Data engineers shipping production pipelines: ingest, transform, serve & trust the data.",
    description:
      "Stand up data pipelines you can run in production and trust. Reach for this when you're moving data end to end — streaming ingestion off Kafka, batch transforms in Spark, an analytics store in ClickHouse — and need quality checks and query tuning so the numbers downstream are correct and fast. Built for the engineer who owns the pipeline, not the analyst querying its output.",
    author: 'Skill Me',
    category: 'data',
    tags: ['data-engineering', 'pipelines', 'data'],
    featured: false,
    verified: true,
    free: true,
    install_count: 14200,
    skill_slugs: [
      'kafka-pipelines', 'spark-jobs', 'clickhouse-analytics',
      'data-quality', 'time-series', 'ml-feature-engineering',
      'sql-query-optimizer', 'mongodb-expert',
    ],
  },
  {
    slug: 'startup-fundraising',
    name: 'Startup Fundraising',
    tagline: "For founders raising a round: pitch, narrative, market, investor updates, and term sheets.",
    description:
      "Reach for this when you're a founder running a fundraise and want every artifact investors actually judge you on. Land the cold intro and tell a fundraising story that earns the meeting, size the market defensibly, pressure-test your Series A readiness and data room, and decode the term sheet before you sign — then keep investors close with crisp monthly updates. The end-to-end founder playbook from first outreach to closed round.",
    author: 'Skill Me',
    category: 'business',
    tags: ['fundraising', 'startup', 'investors'],
    featured: false,
    verified: true,
    free: true,
    install_count: 11800,
    skill_slugs: ["fundraising-narrative", "market-sizing", "fpa-model", "vc-pitch-email", "series-a-readiness", "term-sheet-explainer", "investor-update-writer"],
  },
  {
    slug: 'technical-writing-studio',
    name: 'Technical Writing Studio',
    tagline: "Ship the docs people read — READMEs, guides, changelogs, API references, and SOPs.",
    description:
      "Turn what you built into documentation people actually read. Generate a README, write tutorials and how-to guides, ship user-facing changelogs, stand up help articles and FAQs, design clear API references, document recurring work as SOPs, and produce authoritative whitepapers. Reach for this when a feature is done but undocumented and you need clear, accurate, maintainable docs fast — not a blank page.",
    author: 'Skill Me',
    category: 'writing',
    tags: ['technical-writing', 'docs', 'writing'],
    featured: false,
    verified: true,
    free: true,
    install_count: 10400,
    skill_slugs: [
      'readme-generator', 'technical-blog-engine', 'changelog-writer',
      'help-documentation', 'api-design', 'process-doc', 'whitepapers',
    ],
  },
  {
    slug: 'bi-and-dashboards',
    name: 'BI & Dashboards',
    tagline: "For analysts: ship a dashboard execs trust, plus the story that makes the numbers land.",
    description:
      "Reach for this when you have data in a warehouse and a stakeholder who needs to act on it. It takes you from query to a clean, performant dashboard in Tableau or Power BI, then turns the numbers into a headline-first narrative that survives the exec meeting — so the work gets read, not just built.",
    author: 'Skill Me',
    category: 'data',
    tags: ['bi', 'dashboards', 'analytics'],
    featured: false,
    verified: true,
    free: true,
    install_count: 12100,
    skill_slugs: ["power-bi-dax", "tableau-best-practices", "sql-to-insights", "data-story"],
  },
  // ── Phase 2 expansion packs ──
  {
    slug: "customer-support-copilot",
    name: "Customer Support Copilot",
    tagline: "For support teams: resolve in one touch, escalate cleanly, deflect with self-service.",
    description: "Reach for this when you run a support queue and want every ticket to end in a resolution, not a follow-up. Seven skills cover the ticket lifecycle: draft empathetic one-touch replies, build a macro library that still sounds human, de-escalate angry customers and communicate refund decisions safely, write escalations engineering will actually act on, mine CSAT verbatims for the root causes worth fixing, turn resolved tickets into KB articles that deflect the next wave, and diagnose churn to build segmented retention playbooks. The outcome: faster resolutions, smarter escalations, and a queue that shrinks as self-service grows.",
    author: "Skill Me",
    category: "business",
    tags: ["support","customer-success","cx"],
    featured: false,
    verified: true,
    free: true,
    install_count: 18500,
    skill_slugs: ["support-ticket-reply","support-macro-library","escalation-summary","csat-root-cause","kb-article-writer","refund-deescalation","churn-reduction"],
  },
  {
    slug: "designer-to-dev-handoff",
    name: "Designer-to-Dev Handoff",
    tagline: "For designers handing off to engineers: specs so precise the build matches the design.",
    description: "Reach for this when you're handing a design to engineering and you're tired of the build coming back wrong. It gives you the full handoff toolkit — a single source-of-truth handoff doc, precise redline annotations, and dedicated specs for motion and responsive behavior — plus a QA checklist to verify the implementation before sign-off. The result: fewer Slack round-trips, no guesswork at the design-to-code boundary, and shipped UI that matches intent.",
    author: "Skill Me",
    category: "design",
    tags: ["design-handoff","frontend","collaboration"],
    featured: false,
    verified: true,
    free: true,
    install_count: 18400,
    skill_slugs: ["design-qa-checklist","redline-annotation","motion-spec","responsive-spec","design-handoff-doc","prototype-spec","component-api-design","color-accessibility"],
  },
  {
    slug: "document-studio",
    name: "Document Studio",
    tagline: "Consultants, analysts, operators: every business document, polished and decision-ready.",
    description: "Reach for this when the quality of what you ship matters — a board deck, a model someone else will audit, a report a busy reader navigates in two minutes, a one-pager that lands the ask. Each skill enforces the structure, hierarchy, and formatting discipline that separates a document people trust from one they second-guess, so you spend your time on the argument, not the formatting.",
    author: "Skill Me",
    category: "productivity",
    tags: ["documents","decks","reports"],
    featured: false,
    verified: true,
    free: true,
    install_count: 17400,
    skill_slugs: ["slide-deck-builder","spreadsheet-model-builder","formatted-report-writer","data-table-design","one-pager-designer","document-template-system","executive-summary"],
  },
  {
    slug: "engineering-manager-toolkit",
    name: "Engineering Manager Toolkit",
    tagline: "For engineering managers: ship reliably, grow your people, and keep leadership aligned.",
    description: "The operating system for running an engineering team without dropping a ball. Reach for it when the manager job gets real: defending debt investment to leadership, running retros that actually close, hiring without bias, writing reviews that hold up in calibration, catching morale and delivery drift before it shows in attrition, and turning a chaotic week into an exec update that takes 90 seconds to read. Every skill is opinionated and evidence-based, built for a real team under real pressure — not a textbook on management theory.",
    author: "Skill Me",
    category: "productivity",
    tags: ["engineering-management","leadership","teams"],
    featured: false,
    verified: true,
    free: true,
    install_count: 9400,
    skill_slugs: ["tech-debt-prioritizer","sprint-retro-facilitator","hiring-scorecard","eng-status-rollup","performance-review-writer","team-health-check","1on1-agenda","feedback-writer"],
  },
  {
    slug: "incident-response-command",
    name: "Incident Response Command",
    tagline: "For engineers who own production: run incidents calmly and defend reliability on-call.",
    description: "Reach for this when you own a service on-call and want incidents to be routine, not chaos. It carries you through the whole lifecycle — instrument and de-noise your signals, call severity fast, work the runbook, keep customers honestly informed, hand the shift off cleanly, write the blameless postmortem, and turn SLO error budgets into automatic team decisions. The outcome: faster, calmer responses, less alert fatigue, and reliability that holds up instead of eroding. Built for engineers and SREs who carry the pager.",
    author: "Skill Me",
    category: "coding",
    tags: ["sre","incidents","reliability"],
    featured: true,
    verified: true,
    free: true,
    install_count: 14700,
    skill_slugs: ["sev-triage","runbook-writer","status-page-update","oncall-handoff","alert-tuning","error-budget-policy","observability-stack","postmortem-writer"],
  },
  {
    slug: "outbound-sales-engine",
    name: "Outbound Sales Engine",
    tagline: "For AEs and SDRs: run a B2B outbound deal from cold email to close with sharper execution.",
    description: "Reach for this when you own outbound deals and want every stage to land — not generic sales theory. It walks the full motion: write cold outreach that gets replies, prep discovery so you qualify and tailor, demo to the buyer's actual pain, defuse the price/timing/competitor/status-quo objections that stall deals, write a proposal that drives a next step, and run a mutual action plan plus a value-adding follow-up cadence that gets the deal signed instead of going quiet. Built for AEs and SDRs who want sharper execution under deal pressure.",
    author: "Skill Me",
    category: "business",
    tags: ["sales","outbound","b2b"],
    featured: true,
    verified: true,
    free: true,
    install_count: 19600,
    skill_slugs: ["discovery-call-prep","objection-handler","sales-proposal-writer","mutual-action-plan","demo-script","sales-followup-cadence","cold-email-craft"],
  },
  {
    slug: "security-compliance-hardening",
    name: "Security & Compliance Hardening",
    tagline: "AppSec & staff engineers: harden every stage of the SDLC and pass your SOC 2 audit.",
    description: "Reach for this when you own security for an engineering team and need to harden the whole software lifecycle, not just run a scanner. It walks you from design-time threat modeling and supply-chain/dependency risk, through secrets hygiene and security-focused code review, to triaging real exploitable findings out of scanner noise and assembling the evidence that gets you through a SOC 2 audit. Opinionated, senior-level defaults so you ship with confidence and survive the audit without the busywork.",
    author: "Skill Me",
    category: "coding",
    tags: ["security","compliance","appsec"],
    featured: false,
    verified: true,
    free: true,
    install_count: 14300,
    skill_slugs: ["threat-model-stride","dependency-risk-audit","secrets-hygiene","soc2-evidence-helper","vulnerability-triage","secure-code-review","security-audit","pii-scrubber"],
  },
  {
    slug: "ux-research-discovery",
    name: "UX Research & Discovery",
    tagline: "For UX researchers: interviews, surveys, and usability tests that change what ships.",
    description: "Reach for this when you own a research question end to end and need the output to actually move a product decision — not sit in a deck nobody acts on. It carries you from study design (non-leading interview guides, unbiased surveys, defensible usability test plans) through synthesis (themes, Jobs To Be Done, evidence-based personas) to a stakeholder readout that leads with the \"so what\" and a confidence level. Every skill encodes senior-researcher defaults — bias traps caught before fielding, insights tied to participant counts, recommendations specific enough to disagree with.",
    author: "Skill Me",
    category: "research",
    tags: ["ux-research","discovery","product"],
    featured: false,
    verified: true,
    free: true,
    install_count: 11800,
    skill_slugs: ["interview-guide-builder", "survey-designer", "usability-test-plan", "interview-synthesis", "jtbd-extractor", "user-persona", "research-readout"],
  },

  // ── Phase 3 expansion packs ──
  {
    slug: "creator-studio",
    name: "Creator Studio",
    tagline: "For solo video & podcast creators: script, hook, package, and distribute every episode.",
    description: "Reach for Creator Studio when you run a video or podcast channel alone and the production line keeps stalling — a blank script, a weak hook, a thumbnail that doesn't earn the click, show notes you skip, and a calendar you can't sustain. It carries one episode end to end: write a retention-built YouTube script, open short-form with a scroll-stopping hook, package the video with a high-CTR thumbnail and title, ship complete podcast show notes, repurpose the source into platform-native posts, and lock a cadence you can actually keep. Built for creators who publish every week, not occasionally.",
    author: "Skill Me",
    category: "writing",
    tags: ["content-creator","video","social"],
    featured: false,
    verified: true,
    free: true,
    install_count: 19400,
    skill_slugs: ["creator-content-calendar", "youtube-script-writer", "video-hook-writer", "thumbnail-concept", "show-notes-writer", "content-repurposing"],
  },
  {
    slug: "data-science-ml",
    name: "Data Science & ML",
    tagline: "For ML teams: ship a trustworthy model end-to-end, from EDA to production drift alerts.",
    description: "Reach for this pack when you own an ML model and need it to survive contact with production. It walks the full lifecycle as a connected discipline: profile the data before you model, engineer leakage-safe features, track experiments so results reproduce, evaluate honestly against real baselines and error slices (for both classic models and LLM systems), document the model for the people it affects, and watch for drift so you retrain on evidence instead of vibes. The payoff is a model you can defend to stakeholders and trust over the long haul — not a notebook that worked once.",
    author: "Skill Me",
    category: "data",
    tags: ["machine-learning","data-science","mlops"],
    featured: false,
    verified: true,
    free: true,
    install_count: 19400,
    skill_slugs: ["eda-playbook", "ml-feature-engineering", "feature-store-design", "experiment-tracking", "model-evaluation-report", "model-card-writer", "data-drift-monitor"],
  },
  {
    slug: "educators-toolkit",
    name: "Educator's Toolkit",
    tagline: "Plan the term, run the lesson, and grade it fairly — guidance for classroom teachers.",
    description: "For classroom teachers who want to spend less time planning and more time teaching. Reach for this pack when you are mapping a term, designing a lesson, adapting it for a mixed-readiness room, and turning student work into fair grades and feedback that actually moves learners forward — plus support for building study plans and synthesizing source material. The guidance is opinionated and pedagogy-first, not generic templates, so each step starts from real structure instead of a blank page.",
    author: "Skill Me",
    category: "writing",
    tags: ["education","teaching","curriculum"],
    featured: false,
    verified: true,
    free: true,
    install_count: 18400,
    skill_slugs: ["curriculum-mapper", "lesson-plan-builder", "differentiated-instruction", "quiz-generator", "rubric-builder", "student-feedback-writer"],
  },
  {
    slug: "finance-accounting-ops",
    name: "Finance & Accounting Ops",
    tagline: "Close the books, build the forecast, and control spend with precision.",
    description: "The finance operating system for controllers and operators at a growing company: run a clean month-end close, build statements that tie out, explain every budget variance, forecast cash and runway, model the annual plan from real drivers, and enforce spend. Reach for it when you own the close calendar and the board deck and need structured, opinionated guidance without the consulting bill.",
    author: "Skill Me",
    category: "business",
    tags: ["finance","accounting","fpa"],
    featured: false,
    verified: true,
    free: true,
    install_count: 11200,
    skill_slugs: ["month-end-close", "financial-statement-builder", "budget-vs-actual", "cash-flow-forecast", "fpa-model", "expense-policy"],
  },
  {
    slug: "health-and-longevity",
    name: "Health & Longevity",
    tagline: "For people building a lasting health practice: train, eat, sleep, and move with intent.",
    description: "Reach for this when you want a health routine that holds up over years, not a 6-week crash plan. It builds a foundation of strength and Zone 2 aerobic conditioning, then layers in nutrition, sleep, mobility, and injury-resilient movement — and helps you read your own bloodwork so you walk into the doctor with the right questions. Use it to assemble a complete weekly routine or to fix the one pillar that's slipping. General wellness education only, not a substitute for professional medical advice.",
    author: "Skill Me",
    category: "personal",
    tags: ["health","fitness","longevity"],
    featured: false,
    verified: true,
    free: true,
    install_count: 18600,
    skill_slugs: ["bloodwork-explainer", "nutrition-planner", "strength-training-plan", "injury-prehab", "mobility-routine", "sleep-optimizer", "longevity-protocol", "zone-2-cardio-plan"],
  },
  {
    slug: "lifecycle-marketing",
    name: "Lifecycle & Email Marketing",
    tagline: "For lifecycle marketers: turn signups into retained users and keep email in the inbox.",
    description: "Reach for this when you own a lifecycle or email program and need it to actually move retention, not just ship more sends. It takes you from a stage-by-stage journey map and behavioral segments through onboarding drips, multi-channel push, and dormant-user win-backs, with deliverability practices guarding your sender reputation so the work lands in the inbox. The payoff: a coherent program where every message has a clear job and a measurable signal, instead of disconnected blasts that burn your list.",
    author: "Skill Me",
    category: "writing",
    tags: ["lifecycle","email","retention"],
    featured: false,
    verified: true,
    free: true,
    install_count: 14800,
    skill_slugs: ["lifecycle-journey-map","email-drip-builder","win-back-campaign","segmentation-strategy","push-notification-copy","email-deliverability","email-newsletter-pro","churn-reduction"],
  },
  {
    slug: "performance-marketing",
    name: "Performance Marketing",
    tagline: "For paid marketers: cut wasted spend and scale every channel to profitable CAC.",
    description: "Reach for this when paid spend is growing faster than profit and you need to find the leak before you scale. It runs the full acquisition loop as one discipline — audit channels for waste, sharpen audience targeting, test creative and landing pages with real statistical rigor, then pace and reallocate budget to the campaigns clearing your CAC target. The outcome is a ranked, dollar-quantified action list every cycle, not another dashboard to stare at.",
    author: "Skill Me",
    category: "business",
    tags: ["marketing","paid-ads","growth"],
    featured: false,
    verified: true,
    free: true,
    install_count: 19600,
    skill_slugs: ["paid-acquisition-audit","ad-creative-testing","landing-page-cro","marketing-attribution","budget-pacing","audience-targeting","landing-page-copy","ab-test-analyzer"],
  },
  {
    slug: "personal-finance-mastery",
    name: "Personal Finance Mastery",
    tagline: "Take control of your money: budget, kill debt, build savings, retire on track.",
    description: "Reach for this when you want to stop reacting to money and start running it on a plan. It walks the full personal-finance arc with opinionated, do-it-now frameworks: build a zero-based budget, size and fund an emergency cushion, sequence your debt payoff, pressure-test big purchases, cut your tax bill, and project whether your savings rate actually gets you to retirement. The outcome is a concrete plan grounded in your real numbers, not generic advice — so every dollar has a job and you know your trajectory.",
    author: "Skill Me",
    category: "personal",
    tags: ["money","personal-finance","budgeting"],
    featured: false,
    verified: true,
    free: true,
    install_count: 14800,
    skill_slugs: ["budget-builder","debt-payoff-planner","tax-optimization","retirement-projection","emergency-fund-planner","big-purchase-decision","financial-planner","investment-basics"],
  },

  // ── Phase 4 expansion packs ──
  {
    slug: "brand-visual-identity",
    name: "Brand & Visual Identity",
    tagline: "For founders and brand designers: ship an identity that looks intentional from day one.",
    description: "Turn a vague brand idea into a coherent, defensible visual identity — without a costly agency round. Reach for this pack when you are naming a new brand, briefing a designer, or building the look from scratch: it walks you from name and moodboard through color, type, and icons, locks in reading-order and hierarchy, and ends with a guidelines doc any teammate can apply. Opinionated, accessibility-aware, and structured so each decision builds on the last — for founders, brand strategists, and designers who want a brand that looks deliberate, not assembled.",
    author: "Skill Me",
    category: "design",
    tags: ["branding","visual-identity","design"],
    featured: false,
    verified: true,
    free: true,
    install_count: 19300,
    skill_slugs: ["logo-brief-writer","color-palette-builder","typography-system","moodboard-builder","visual-hierarchy","brand-naming","brand-guidelines","icon-system"],
  },
  {
    slug: "skill-builder-studio",
    name: "Skill Builder Studio",
    tagline: "For skill authors: take a Claude Agent Skill from blank file to A+, tested, and packed.",
    description: "The authoring loop for people who build Claude Agent Skills. Reach for it when a skill needs to go from idea to shippable: draft a new one from scratch, audit an existing one to an A+ bar, sharpen the description so it triggers reliably, prove the triggers fire with live tests, and assemble members into a pack that holds together. End state is a skill (or pack) you can publish with confidence, not a to-do list.",
    author: "Skill Me",
    category: "coding",
    tags: ["agent-skills","meta","authoring"],
    featured: true,
    verified: true,
    free: true,
    install_count: 14200,
    skill_slugs: ["skill-creator", "skill-auditor", "skill-description-writer", "skill-tester", "skill-pack-curator"],
  },

  // ── Phase 5 expansion packs (gap-fill: g-2026-06) ──
  {
    slug: "database-performance",
    name: "Database Performance & Administration",
    tagline: "For backend engineers: make slow queries fast and keep production Postgres healthy.",
    description: "Reach for this when a production database is slow or strained and you need a verifiable fix, not folklore. It walks the real diagnose-to-resolve path: catch N+1s in your ORM, read an EXPLAIN plan down to the bottleneck node, advise the right index, rewrite pathological SQL, decide when to partition, size connection pools, ship migrations with zero-downtime locking, and chase down stale reads from replica lag. Every fix is EXPLAIN-checkable, so you ship the change knowing it actually moved the number.",
    author: "Skill Me",
    category: "data",
    tags: ["database","performance","postgres","sql"],
    featured: true,
    verified: true,
    free: true,
    install_count: 21800,
    skill_slugs: ["n-plus-one-hunter", "explain-plan-reader", "index-advisor", "query-rewriter", "partition-planner", "connection-pool-tuner", "migration-safety-checker", "replication-lag-debugger"],
  },
  {
    slug: "legacy-modernization",
    name: "Legacy Modernization & Migration",
    tagline: "For engineers in legacy code: modernize incrementally, no big-bang rewrite.",
    description: "Reach for this when you inherit a business-critical codebase that has to keep running while you drag it onto a modern stack. Plan a strangler-fig migration that runs old and new side by side, carve one safe bounded-context seam out of a monolith, drive major framework and language-version upgrades as small reversible CI-gated PRs, recover the business rules buried in tangled code, pin current behavior with characterization tests before you touch it, audit dependency risk as you upgrade, and delete dead code with evidence — so nothing breaks while everything moves.",
    author: "Skill Me",
    category: "coding",
    tags: ["legacy","migration","refactoring","modernization"],
    featured: true,
    verified: true,
    free: true,
    install_count: 16400,
    skill_slugs: ["strangler-fig-planner","framework-upgrader","language-version-migrator","business-rule-extractor","characterization-test-writer","dead-code-eliminator","monolith-decomposer","dependency-risk-audit","tdd-expert"],
  },
  {
    slug: "qa-test-automation",
    name: "QA & Test Automation",
    tagline: "For engineers who don't trust their test suite: catch real bugs and kill the flake.",
    description: "Reach for this when your suite is green but you don't believe it — high coverage that misses the bug, tests that flake in CI, mocks that pass while production breaks. It takes a suite from \"runs\" to \"trustworthy\": prove which gaps actually matter, root-cause flakiness instead of retrying around it, and use mutation testing to expose assertions that verify nothing. Pull it in before a release cut or when a passing build still ships regressions.",
    author: "Skill Me",
    category: "coding",
    tags: ["testing","qa","automation","quality"],
    featured: false,
    verified: true,
    free: true,
    install_count: 15200,
    skill_slugs: ["flaky-test-detangler","coverage-gap-finder","test-data-builder","contract-test-writer","e2e-scenario-author","mock-stub-designer","mutation-test-runner","playwright-testing","tdd-expert"],
  },
  {
    slug: "mobile-app-engineering",
    name: "Mobile App Engineering",
    tagline: "For mobile engineers: build native + cross-platform apps and ship them past store review.",
    description: "The mobile stack the catalog was missing. Reach for it when you own an iOS, Android, Flutter, or React Native app end to end: build UIs with correct state flow and no recomposition jank, add local-first offline sync with real conflict resolution, wire APNs/FCM push from token to tap, profile dropped frames and memory leaks against a frame budget, and get through App Store Connect and Play Console submission without the usual signing and privacy-form rejections.",
    author: "Skill Me",
    category: "coding",
    tags: ["mobile","ios","android","cross-platform"],
    featured: true,
    verified: true,
    free: true,
    install_count: 14600,
    skill_slugs: ["swift-ui","react-native-pro","jetpack-compose-builder","flutter-widget-architect","mobile-offline-sync","push-notification-wirer","mobile-perf-profiler","app-store-release-prep"],
  },
  {
    slug: "api-integration-engineering",
    name: "API & Integration Engineering",
    tagline: "For backend engineers: make every API you build or consume survive production.",
    description: "Reach for this when an integration has to be bulletproof — payments that can't double-charge, webhooks you don't control, third-party APIs that throttle or fall over, and contracts that change under you. It turns the hard-won production patterns into skills: idempotent writes, hardened webhook receivers, correct backoff under rate limits, circuit breakers and bulkheads for flaky upstreams, cursor pagination and delta sync, typed clients from OpenAPI, and date-pinned versioning with a real deprecation path. Install it before the integration that, if it breaks, pages you at 3am.",
    author: "Skill Me",
    category: "coding",
    tags: ["api","integration","webhooks","reliability"],
    featured: false,
    verified: true,
    free: true,
    install_count: 17300,
    skill_slugs: ["idempotency-enforcer","webhook-receiver-hardener","rate-limit-handler","circuit-breaker-builder","api-versioning-strategist","pagination-and-sync-engineer","api-client-generator","api-design","oauth-flow"],
  },
  {
    slug: "seo-organic-growth",
    name: "SEO & Organic Growth Engine",
    tagline: "For SEO leads: take one keyword to a ranked, AI-search-ready page — research to refresh.",
    description: "Reach for this when you own a keyword and need it to actually rank and get cited — not just a pile of SEO tips. It runs the full organic-search loop as discrete, hand-off-able steps: cluster keywords into a pillar/cluster plan, lock the right page type to intent, close coverage gaps against what already ranks, ship click-earning titles and metas, wire internal links for topical authority, and engineer answer blocks that AI Overviews, ChatGPT, and Perplexity quote verbatim — then catch decaying pages before they slip. Use it to turn a keyword export into a publishing roadmap, or to diagnose why a well-built page won't move.",
    author: "Skill Me",
    category: "business",
    tags: ["seo","organic-growth","content","aeo"],
    featured: true,
    verified: true,
    free: true,
    install_count: 20400,
    skill_slugs: ["keyword-cluster-builder","search-intent-classifier","serp-gap-analyzer","meta-title-optimizer","internal-linking-mapper","aeo-answer-blockifier","content-refresh-auditor","seo-optimizer","content-brief"],
  },
  {
    slug: "social-media-studio",
    name: "Social Media Manager Studio",
    tagline: "A month of on-brand posts, repurposed everywhere, in an afternoon.",
    description: "Reach for this when you run a brand's social presence alone and the calendar never stops. It takes one idea from a planned multi-platform calendar to posts that sound native on every channel — captions, hooks, LinkedIn posts, X threads, and swipe-through carousels — then repurposes it across feeds, sizes the right hashtag set, and drafts on-brand replies to the comments and DMs that follow. The output is a consistent, channel-native cadence without a content team.",
    author: "Skill Me",
    category: "writing",
    tags: ["social-media","content","marketing","community"],
    featured: false,
    verified: true,
    free: true,
    install_count: 23600,
    skill_slugs: ["social-content-calendar","social-caption-writer","social-hook-generator","cross-platform-reformatter","hashtag-strategist","engagement-reply-drafter","carousel-scripter","linkedin-post-writer","tweet-thread-builder"],
  },
  {
    slug: "ecommerce-dtc-ops",
    name: "E-commerce & DTC Operations",
    tagline: "Conversion copy for every DTC touchpoint — product page to abandoned-cart flow.",
    description: "Reach for this when you run a DTC or e-commerce store and need on-brand copy that converts across the whole funnel — not a one-off blurb. Turn spec sheets into benefit-led product pages, scale them across every variant without duplicate-content penalties, write Amazon listings that survive the rules, mine reviews into objection-killing PDP FAQs, rank category and \"vs\"-comparison pages for high-intent buyers, and recover lost carts with a margin-aware email sequence. The copy stack a lean DTC team would otherwise hire a specialist for.",
    author: "Skill Me",
    category: "business",
    tags: ["ecommerce","dtc","conversion","copywriting"],
    featured: false,
    verified: true,
    free: true,
    install_count: 18900,
    skill_slugs: ["product-description-writer","amazon-listing-optimizer","variant-copy-scaler","review-to-faq-builder","category-page-copywriter","abandoned-cart-sequence","comparison-page-builder","landing-page-cro","email-drip-builder"],
  },
  {
    slug: "people-ops-recruiting",
    name: "People Ops & Recruiting Toolkit",
    tagline: "For hiring managers without an HR team: run a fair, structured hire end to end.",
    description: "Reach for this when you own a req but have no recruiting team behind you and need every hire to be fair, consistent, and defensible. It runs the whole funnel as one connected system: source passive candidates, write an inclusive JD and scrub it for bias, screen resumes against a weighted rubric, build STAR question kits and interviewer scorecards, synthesize the debrief into a calibrated hire/no-hire call, send careful offers and respectful rejections, then stand up a 30/60/90 onboarding plan. Each stage works from shared, job-derived criteria, and every skill keeps a human as the decision-maker with explicit fairness bounds — so you move fast without cutting the corners that create bias or legal exposure.",
    author: "Skill Me",
    category: "business",
    tags: ["hiring","recruiting","people-ops","management"],
    featured: false,
    verified: true,
    free: true,
    install_count: 13100,
    skill_slugs: ["job-description-writer","jd-bias-scrubber","screening-rubric-builder","interview-question-kit","candidate-outreach-personalizer","offer-rejection-writer","onboarding-plan-builder","interview-debrief-synthesizer","hiring-scorecard","feedback-writer"],
  },
  {
    slug: "gym-growth-engine",
    name: "Gym Growth Engine",
    tagline: "For gym owners: fill the calendar, close consults, and scale on proven unit economics.",
    description: "Turn a single-location gym into a predictable growth machine using the offer, lead-gen, sales, and money-model playbooks behind Gym Launch and Acquisition.com. Reach for it when you need more members but ads stall, when your offer or pricing isn't converting, when consults leak or members churn, or when you're stuck in the day-to-day and need KPIs, referrals, and hires to scale. Each skill ships runnable calculators and ready-to-send templates, so you leave with a decision and an artifact — not theory.",
    author: "Skill Me",
    category: "business",
    tags: ["gym","fitness","sales","unit-economics"],
    featured: false,
    verified: true,
    free: true,
    install_count: 9600,
    repo_url: "https://github.com/aouellets/gym-growth-engine",
    skill_slugs: ["gym-money-model","grand-slam-offer-builder","gym-pricing-and-guarantees","core-four-lead-engine","gym-transformation-challenge","gym-meta-ads-funnel","closer-sales-script","objection-handling-and-speed-to-lead","retention-and-churn-killer","referral-and-affiliate-system","kpi-scoreboard-and-cadence","hiring-a-players-and-sops"],
  },
  {
    slug: "founder-fundraising-os",
    name: "Founder Fundraising OS",
    tagline: "Everything a founder needs to raise a round — from deciding the stage to wired funds.",
    description: "The complete operating system for raising venture capital, end to end. Decide your stage, amount, and valuation; run an honest readiness audit; model your cap table and dilution; build the pitch deck and narrative; size the market and financials; assemble a staged data room; shape the team story and key hires. Then run the raise like a sales process: target the right VCs and angels with warm paths, manage the pipeline to manufacture momentum, drill the pitch and the hard Q&A, pass diligence, negotiate the term sheet, choose SAFE vs priced, and drive the close to cash. Every skill is operator-grade with concrete checklists and deliverables.",
    author: "Skill Me",
    category: "business",
    tags: ["fundraising","startup","venture-capital","founder"],
    featured: true,
    verified: true,
    free: true,
    install_count: 0,
    repo_url: "https://github.com/aouellets/founder-fundraising-os",
    skill_slugs: [
      "fundraising-stage-selector","fundraise-readiness-audit","cap-table-manager",
      "market-sizing","financial-planner",
      "fundraising-narrative","pitch-deck-builder","data-room-builder",
      "fundraise-team-hiring",
      "investor-targeting","vc-pitch-email","investor-pipeline-crm","investor-update-writer",
      "pitch-practice-coach","series-a-readiness","due-diligence-checklist",
      "term-sheet-explainer","safe-vs-priced-round","term-sheet-negotiation","fundraise-closing-mechanics",
    ],
  },
  {
    slug: "remotion-video-production",
    name: "Remotion Video Production",
    tagline: "Turn natural language briefs into rendered MP4s using Claude Code and Remotion — covers project setup, composition generation, and the render/iterate loop.",
    description: "Produce software product demos, feature-announcement videos, and marketing animations without a video editor or motion-design background. Three skills that work in sequence — Remotion Setup scaffolds a project wired for Claude Code Agent Skills, Remotion Compose turns a natural-language brief into a complete React/TypeScript composition, and Remotion Render handles export plus the feedback-and-re-render loop — and each is independently useful once a project is underway. Built for developers, product teams, and solo founders who want to describe a video and get a rendered MP4 back.",
    author: "Skill Me",
    category: "coding",
    tags: ["remotion", "video", "react", "claude-code"],
    featured: true,
    verified: true,
    free: true,
    install_count: 0,
    skill_slugs: [
      "remotion-setup", "remotion-compose", "remotion-render",
    ],
  },
  {
    slug: "resume-toolkit",
    name: "Resume Toolkit",
    tagline: "Write a resume from scratch or critique the one you have — ATS-optimized, seniority-aware, delivered as .docx.",
    description: "A two-skill loop for getting a resume right. Resume Writer runs a short elicitation, then drafts a complete ATS-optimized resume — tailored summary, STAR-format action-verb bullets quantified wherever possible, clean standard sections — and exports a .docx. Resume Reviewer critiques an existing resume against a scored rubric (impact, ATS readiness, clarity, format/length), returns a prioritized fix list, rewrites the weakest bullets, and runs a keyword gap analysis against a target job description — also as a .docx. The two hand off to each other: review, then rebuild clean. Both are seniority-aware (IC vs manager vs executive), carry a strong action-verb library, follow ATS best practices throughout, and give honest, direct feedback.",
    author: "Skill Me",
    category: "personal",
    tags: ["resume", "career", "job-search", "ats"],
    featured: true,
    verified: true,
    free: true,
    install_count: 0,
    repo_url: "https://github.com/aouellets/resume-toolkit",
    skill_slugs: [
      "resume-writer", "resume-reviewer",
    ],
  },

]
