import type { PackCategory } from './types'

/**
 * Canonical pack catalog — the single source of truth shared by the database
 * seeder (`scripts/seed-packs.ts`) and the app's offline fallback
 * (`SEED_PACKS` in `lib/packs.ts`). Keeping one list here prevents the two from
 * drifting (and the per-pack skill count from going stale).
 *
 * Every entry in `skill_slugs` must be a real skill slug from
 * `lib/seed-data.ts`; the seeder warns on any that don't resolve.
 *
 * This module is intentionally free of `server-only` and runtime dependencies so
 * the tsx-run seed script can import it directly.
 */
export interface PackDefinition {
  slug: string
  name: string
  tagline: string
  description: string
  author: string
  category: PackCategory
  tags: string[]
  featured: boolean
  verified: boolean
  free: boolean
  install_count: number
  repo_url?: string             // GitHub repo for this pack (starrable)
  skill_slugs: string[]
}

export const PACK_DEFINITIONS: PackDefinition[] = [
  // ── Launch packs ────────────────────────────────────────────────────────
  {
    slug: 'solo-founder-stack',
    name: 'Solo Founder Stack',
    tagline: 'Everything a solo founder needs from idea to first $10k MRR.',
    description:
      'A curated collection for founders building alone. Covers investor updates, competitive intelligence, pricing strategy, cold email, landing page copy, and unit economics. Built from what actually gets used in the first 18 months.',
    author: 'Skill Me',
    category: 'business',
    tags: ['startups', 'founder', 'business'],
    featured: true,
    verified: true,
    free: true,
    install_count: 14800,
    skill_slugs: [
      'investor-update-writer', 'competitive-intelligence', 'pricing-strategy',
      'cold-email-craft', 'landing-page-copy', 'go-to-market-planner',
      'unit-economics', 'fact-checker',
      'financial-planner', 'market-sizing', 'fundraising-narrative',
    ],
  },
  {
    slug: 'design-system-builder',
    name: 'Design System Builder',
    tagline: 'From tokens to components to documentation — the complete design system workflow.',
    description:
      'Build a production design system end to end. Covers design token systems, component API design, color accessibility, dark mode, icon systems, and prototype specs.',
    author: 'Skill Me',
    category: 'design',
    tags: ['design-system', 'design', 'components'],
    featured: true,
    verified: true,
    free: true,
    install_count: 9200,
    skill_slugs: [
      'design-token-system', 'component-api-design', 'color-accessibility',
      'dark-mode-design', 'icon-system', 'prototype-spec',
      'animation-system', 'anthropic-frontend-design',
    ],
  },
  {
    slug: 'content-marketing-engine',
    name: 'Content Marketing Engine',
    tagline: 'LinkedIn, Twitter, blog, newsletter — one pack, every channel.',
    description:
      'A full content marketing stack. Includes LinkedIn posts, tweet threads, technical blog, email newsletters, landing page copy, case studies, and brand voice.',
    author: 'Skill Me',
    category: 'writing',
    tags: ['content', 'marketing', 'writing'],
    featured: true,
    verified: true,
    free: true,
    install_count: 22400,
    skill_slugs: [
      'linkedin-post-writer', 'tweet-thread-builder', 'technical-blog-engine',
      'email-newsletter-pro', 'landing-page-copy', 'case-study-builder',
      'brand-guidelines', 'content-brief',
    ],
  },
  {
    slug: 'engineering-workflow',
    name: 'Engineering Workflow',
    tagline: 'The git, review, and release workflow every senior engineer already uses.',
    description:
      'Commit messages, PR descriptions, changelogs, readmes, code review, TypeScript strict mode, and TDD — the core workflow skills that separate professional engineers.',
    author: 'Skill Me',
    category: 'coding',
    tags: ['git', 'workflow', 'engineering'],
    featured: true,
    verified: true,
    free: true,
    install_count: 31600,
    skill_slugs: [
      'git-commit-writer', 'pr-description-writer', 'changelog-generator',
      'readme-generator', 'code-review-checklist', 'typescript-strict',
      'tdd-expert', 'karpathy-behavioral-rules',
    ],
  },
  {
    slug: 'legal-team-starter',
    name: 'Legal Team Starter',
    tagline: 'NDA triage, contract review, terms drafting — the essentials for in-house legal.',
    description:
      'Skills for legal teams and founders handling their own legal work. Covers terms of service, employment contract flags, and regulatory scanning.',
    author: 'Skill Me',
    category: 'business',
    tags: ['legal', 'compliance', 'contracts'],
    featured: false,
    verified: true,
    free: true,
    install_count: 7400,
    skill_slugs: [
      'terms-of-service', 'employment-contract',
      'regulatory-scan', 'fact-checker',
    ],
  },
  {
    slug: 'data-analyst-toolkit',
    name: 'Data Analyst Toolkit',
    tagline: 'From raw data to board-ready insights, every step covered.',
    description:
      'The complete data analysis workflow: SQL to insights, pandas, A/B tests, funnel analysis, customer analytics, and data storytelling.',
    author: 'Skill Me',
    category: 'data',
    tags: ['analytics', 'data', 'sql'],
    featured: false,
    verified: true,
    free: true,
    install_count: 18200,
    skill_slugs: [
      'sql-to-insights', 'pandas-expert', 'ab-test-analyzer',
      'funnel-analysis', 'customer-analytics', 'data-story',
      'revenue-modeling',
    ],
  },
  {
    slug: 'saas-growth-stack',
    name: 'SaaS Growth Stack',
    tagline: 'Acquisition, activation, retention — the full SaaS growth toolkit.',
    description:
      'Everything you need to grow a SaaS product. Covers growth modeling, churn reduction, expansion revenue, customer success QBRs, product analytics, and unit economics.',
    author: 'Skill Me',
    category: 'business',
    tags: ['saas', 'growth', 'product'],
    featured: false,
    verified: true,
    free: true,
    install_count: 16400,
    skill_slugs: [
      'growth-model', 'churn-reduction', 'expansion-revenue',
      'customer-success-qbr', 'product-analytics', 'unit-economics',
      'saas-pricing',
    ],
  },
  {
    slug: 'remote-team-toolkit',
    name: 'Remote Team Toolkit',
    tagline: 'Run a tight remote team without drowning in meetings.',
    description:
      'Async communication, meeting notes, weekly reviews, 1:1 agendas, OKRs, and feedback delivery — the full stack for high-functioning remote teams.',
    author: 'Skill Me',
    category: 'productivity',
    tags: ['remote', 'teams', 'management'],
    featured: false,
    verified: true,
    free: true,
    install_count: 12800,
    skill_slugs: [
      'meeting-notes-to-actions', 'weekly-review', 'okr-builder',
      'feedback-writer', 'stakeholder-update', 'async-communication',
      '1on1-agenda',
    ],
  },
  {
    slug: 'devops-platform-engineer',
    name: 'DevOps & Platform Engineering',
    tagline: 'Infrastructure as code, CI/CD, containers, and observability.',
    description:
      'Terraform, GitHub Actions, Docker Compose, Kubernetes, and observability — the tools platform engineers use every day, encoded as skills.',
    author: 'Skill Me',
    category: 'coding',
    tags: ['devops', 'infrastructure', 'platform'],
    featured: false,
    verified: true,
    free: true,
    install_count: 19400,
    skill_slugs: [
      'terraform-expert', 'github-actions', 'docker-compose-wizard',
      'kubernetes-basics', 'observability-stack', 'env-doctor',
      'security-audit',
    ],
  },
  {
    slug: 'academic-researcher',
    name: 'Academic Researcher',
    tagline: 'Literature reviews, systematic reviews, citations, and policy briefs.',
    description:
      'A skill pack for academics and researchers. Covers systematic reviews, literature synthesis, citation management, academic essays, and policy briefs.',
    author: 'Skill Me',
    category: 'research',
    tags: ['academic', 'research', 'writing'],
    featured: false,
    verified: true,
    free: true,
    install_count: 8600,
    skill_slugs: [
      'systematic-review', 'literature-review', 'citation-tracker',
      'academic-essay', 'policy-brief', 'fact-checker',
    ],
  },

  // ── Expansion packs ─────────────────────────────────────────────────────
  {
    slug: 'personal-operating-system',
    name: 'Personal Operating System',
    tagline: 'Build the habits, focus, and systems that compound — your life, run like a product.',
    description:
      'A complete operating system for your personal life. Build durable habits, fix your sleep, study faster, journal with intent, make better decisions, manage stress, and run a second brain — the routines high-performers rely on.',
    author: 'Skill Me',
    category: 'personal',
    tags: ['personal', 'habits', 'productivity'],
    featured: true,
    verified: true,
    free: true,
    install_count: 13400,
    skill_slugs: [
      'habit-builder', 'sleep-optimizer', 'study-system',
      'journal-framework', 'decision-making', 'stress-management',
      'goals-accountability', 'second-brain', 'deep-work-planner',
    ],
  },
  {
    slug: 'ai-engineer-toolkit',
    name: 'AI Engineer Toolkit',
    tagline: 'Ship LLM features that work — prompts, evals, agents, and MCP servers.',
    description:
      "The modern AI engineer's toolkit. Design prompts that hold up, build MCP servers, evaluate LLM output rigorously, orchestrate multi-step agents, run deep research, engineer ML features, and handle errors gracefully.",
    author: 'Skill Me',
    category: 'coding',
    tags: ['ai', 'llm', 'agents'],
    featured: true,
    verified: true,
    free: true,
    install_count: 24600,
    skill_slugs: [
      'prompt-engineer', 'mcp-builder', 'llm-evaluation',
      'agent-orchestration', 'deep-research', 'ml-feature-engineering',
      'error-handling',
    ],
  },
  {
    slug: 'product-manager-stack',
    name: 'Product Manager Stack',
    tagline: 'Roadmaps, specs, sprints, and analytics — the PM’s full operating kit.',
    description:
      'Everything a product manager needs to plan and ship. Write roadmaps and specs, define personas, run sprints, set OKRs, read product analytics, map user flows, and write crisp tickets.',
    author: 'Skill Me',
    category: 'productivity',
    tags: ['product', 'pm', 'roadmap'],
    featured: false,
    verified: true,
    free: true,
    install_count: 17200,
    skill_slugs: [
      'product-roadmap', 'technical-spec', 'user-persona',
      'sprint-planning', 'okr-builder', 'product-analytics',
      'user-flow-mapper', 'jira-ticket-writer',
    ],
  },
  {
    slug: 'full-stack-web-dev',
    name: 'Full-Stack Web Dev',
    tagline: 'Next.js to Postgres — build and ship a modern web app end to end.',
    description:
      'The full modern web stack as skills. Next.js App Router, GraphQL and database schema design, OAuth, Stripe billing, Supabase, web performance, and clean API design.',
    author: 'Skill Me',
    category: 'coding',
    tags: ['web', 'fullstack', 'nextjs'],
    featured: false,
    verified: true,
    free: true,
    install_count: 26800,
    skill_slugs: [
      'nextjs-app-router', 'graphql-schema', 'database-schema',
      'oauth-flow', 'stripe-integration', 'supabase-expert',
      'web-performance', 'api-design',
    ],
  },
  {
    slug: 'job-search-kit',
    name: 'Job Search Kit',
    tagline: 'Land the offer — applications, outreach, networking, and negotiation.',
    description:
      'A focused kit for your job hunt. Tailor applications, write cold outreach and a standout LinkedIn presence, build a networking system, and negotiate the offer with confidence.',
    author: 'Skill Me',
    category: 'personal',
    tags: ['career', 'job-search', 'personal'],
    featured: false,
    verified: true,
    free: true,
    install_count: 15600,
    skill_slugs: [
      'job-application', 'salary-negotiation', 'networking-system',
      'linkedin-post-writer', 'cold-email-craft',
    ],
  },
  {
    slug: 'fiction-writers-room',
    name: "Fiction Writer's Room",
    tagline: 'Scenes, voice, and structure — the craft of long-form storytelling.',
    description:
      'For novelists and storytellers. Write vivid scenes, develop a distinct voice through ghostwriting, craft speeches and op-eds, pitch a book proposal, and shape narrative for any audience.',
    author: 'Skill Me',
    category: 'writing',
    tags: ['fiction', 'writing', 'storytelling'],
    featured: false,
    verified: true,
    free: true,
    install_count: 9100,
    skill_slugs: [
      'fiction-scene-writer', 'ghostwriter', 'speech-writer',
      'book-proposal', 'op-ed-writer', 'sermon-writer',
    ],
  },
  {
    slug: 'data-engineering-pipeline',
    name: 'Data Engineering Pipeline',
    tagline: 'Streams, batch, and storage — production data pipelines, encoded.',
    description:
      'Build and run production data pipelines. Kafka streaming, Spark batch jobs, ClickHouse analytics, data quality checks, time-series modeling, ML feature engineering, and query optimization.',
    author: 'Skill Me',
    category: 'data',
    tags: ['data-engineering', 'pipelines', 'data'],
    featured: false,
    verified: true,
    free: true,
    install_count: 14200,
    skill_slugs: [
      'kafka-pipelines', 'spark-jobs', 'clickhouse-analytics',
      'data-quality', 'time-series', 'ml-feature-engineering',
      'sql-query-optimizer', 'mongodb-expert',
    ],
  },
  {
    slug: 'startup-fundraising',
    name: 'Startup Fundraising',
    tagline: 'From first pitch to closed round — the founder’s fundraising playbook.',
    description:
      'Raise your round with confidence. Craft the pitch and fundraising narrative, send investor updates, understand term sheets, prep for Series A and due diligence, size the market, and model the financials.',
    author: 'Skill Me',
    category: 'business',
    tags: ['fundraising', 'startup', 'investors'],
    featured: false,
    verified: true,
    free: true,
    install_count: 11800,
    skill_slugs: [
      'vc-pitch-email', 'fundraising-narrative', 'investor-update-writer',
      'term-sheet-explainer', 'series-a-readiness', 'due-diligence-checklist',
      'market-sizing', 'financial-planner',
    ],
  },
  {
    slug: 'technical-writing-studio',
    name: 'Technical Writing Studio',
    tagline: 'Docs people actually read — READMEs, guides, changelogs, and specs.',
    description:
      'Write technical content that lands. READMEs, developer blogs, changelogs, help docs, API references, process docs, and whitepapers — clear, accurate, and maintainable.',
    author: 'Skill Me',
    category: 'writing',
    tags: ['technical-writing', 'docs', 'writing'],
    featured: false,
    verified: true,
    free: true,
    install_count: 10400,
    skill_slugs: [
      'readme-generator', 'technical-blog-engine', 'changelog-writer',
      'help-documentation', 'api-design', 'process-doc', 'whitepapers',
    ],
  },
  {
    slug: 'bi-and-dashboards',
    name: 'BI & Dashboards',
    tagline: 'Turn warehouse rows into decisions — dashboards and the story behind them.',
    description:
      'The business-intelligence stack. Build dashboards in Tableau and Power BI, turn SQL into insights, narrate the data story, analyze customers, summarize for execs, and spot trends.',
    author: 'Skill Me',
    category: 'data',
    tags: ['bi', 'dashboards', 'analytics'],
    featured: false,
    verified: true,
    free: true,
    install_count: 12100,
    skill_slugs: [
      'tableau-best-practices', 'power-bi-dax', 'sql-to-insights',
      'data-story', 'customer-analytics', 'executive-summary',
      'trend-analysis',
    ],
  },
  // ── Phase 2 expansion packs ──
  {
    slug: "customer-support-copilot",
    name: "Customer Support Copilot",
    tagline: "Six skills to resolve faster, escalate smarter, and turn tickets into self-service.",
    description: "Customer Support Copilot equips support agents and team leads with skills for the full ticket lifecycle — from drafting empathetic one-touch replies to analyzing CSAT verbatims for root causes. Each skill is built around real support workflows: macros that stay human, escalations that get read, and de-escalation that actually works.",
    author: "Skill Me",
    category: "business",
    tags: ["support","customer-success","cx"],
    featured: false,
    verified: true,
    free: true,
    install_count: 18500,
    skill_slugs: ["support-ticket-reply","support-macro-library","escalation-summary","csat-root-cause","kb-article-writer","refund-deescalation","churn-reduction"],
  },
  {
    slug: "designer-to-dev-handoff",
    name: "Designer-to-Dev Handoff",
    tagline: "Precise specs, redlines, and docs that eliminate guesswork at the design-to-code boundary.",
    description: "Five skills covering every stage of the design handoff process — from writing airtight spec documents and redline annotations to defining motion, responsive behavior, and QA checklists. Reduces back-and-forth and ships designs that match intent.",
    author: "Skill Me",
    category: "design",
    tags: ["design-handoff","frontend","collaboration"],
    featured: false,
    verified: true,
    free: true,
    install_count: 18400,
    skill_slugs: ["design-qa-checklist","redline-annotation","motion-spec","responsive-spec","design-handoff-doc","prototype-spec","component-api-design","color-accessibility"],
  },
  {
    slug: "document-studio",
    name: "Document Studio",
    tagline: "Slide decks, reports, models, and templates — every business document, done right.",
    description: "A complete toolkit for producing polished business documents. Covers persuasive slide decks, auditable spreadsheet models, long-form reports, precise data tables, tight one-pagers, and reusable team templates. Built for consultants, analysts, and operators who care about the quality of what they ship.",
    author: "Skill Me",
    category: "productivity",
    tags: ["documents","decks","reports"],
    featured: false,
    verified: true,
    free: true,
    install_count: 17400,
    skill_slugs: ["slide-deck-builder","spreadsheet-model-builder","formatted-report-writer","data-table-design","one-pager-designer","document-template-system","executive-summary"],
  },
  {
    slug: "engineering-manager-toolkit",
    name: "Engineering Manager Toolkit",
    tagline: "Six skills for EMs who manage delivery, people, and stakeholders without the fluff.",
    description: "A curated set of skills for engineering managers covering the recurring high-stakes work: debt prioritization, retrospectives, hiring, status communication, performance reviews, and team health. Each skill is opinionated, evidence-based, and built for a real team context, not a textbook.",
    author: "Skill Me",
    category: "productivity",
    tags: ["engineering-management","leadership","teams"],
    featured: false,
    verified: true,
    free: true,
    install_count: 9400,
    skill_slugs: ["tech-debt-prioritizer","sprint-retro-facilitator","hiring-scorecard","eng-status-rollup","performance-review-writer","team-health-check","1on1-agenda","feedback-writer"],
  },
  {
    slug: "incident-response-command",
    name: "Incident Response Command",
    tagline: "SRE skills for triage, runbooks, alerting, and SLO-driven reliability ops",
    description: "Six skills that cover the full on-call lifecycle: classifying incidents fast, writing runbooks and status updates, handing off shifts cleanly, tuning noisy alerts, and enforcing an error budget policy that turns SLO data into team behavior. Built for engineers who own production.",
    author: "Skill Me",
    category: "coding",
    tags: ["sre","incidents","reliability"],
    featured: true,
    verified: true,
    free: true,
    install_count: 14700,
    skill_slugs: ["sev-triage","runbook-writer","status-page-update","oncall-handoff","alert-tuning","error-budget-policy","observability-stack","postmortem-writer"],
  },
  {
    slug: "outbound-sales-engine",
    name: "Outbound Sales Engine",
    tagline: "Six skills to run a sharper B2B sales process from first call to closed deal.",
    description: "A tightly scoped set of skills for B2B sales professionals covering every stage of an outbound deal cycle. Covers discovery preparation, objection handling, proposals, mutual action plans, demo structure, and follow-up cadence. Built for AEs and SDRs who want sharper execution, not more theory.",
    author: "Skill Me",
    category: "business",
    tags: ["sales","outbound","b2b"],
    featured: true,
    verified: true,
    free: true,
    install_count: 19600,
    skill_slugs: ["discovery-call-prep","objection-handler","sales-proposal-writer","mutual-action-plan","demo-script","sales-followup-cadence","cold-email-craft"],
  },
  {
    slug: "security-compliance-hardening",
    name: "Security & Compliance Hardening",
    tagline: "Threat models, secure reviews, and compliance evidence — ship with confidence.",
    description: "Six skills covering the full defensive security lifecycle for engineering teams: threat modeling, dependency risk, secrets management, SOC 2 compliance, vulnerability triage, and secure code review. Designed for staff engineers and AppSec practitioners who need structured, opinionated guidance without the noise.",
    author: "Skill Me",
    category: "coding",
    tags: ["security","compliance","appsec"],
    featured: false,
    verified: true,
    free: true,
    install_count: 14300,
    skill_slugs: ["threat-model-stride","dependency-risk-audit","secrets-hygiene","soc2-evidence-helper","vulnerability-triage","secure-code-review","security-audit","pii-scrubber"],
  },
  {
    slug: "ux-research-discovery",
    name: "UX Research & Discovery",
    tagline: "Plan, run, and synthesize user research that actually moves product decisions.",
    description: "A end-to-end toolkit for UX researchers and product designers — from writing unbiased interview guides and surveys to extracting JTBD insights, planning usability tests, and delivering crisp stakeholder readouts. Each skill encodes opinionated, senior-researcher defaults with explicit escape hatches for edge cases.",
    author: "Skill Me",
    category: "research",
    tags: ["ux-research","discovery","product"],
    featured: false,
    verified: true,
    free: true,
    install_count: 11800,
    skill_slugs: ["interview-guide-builder","interview-synthesis","survey-designer","jtbd-extractor","usability-test-plan","research-readout","user-persona","user-flow-mapper"],
  },

  // ── Phase 3 expansion packs ──
  {
    slug: "creator-studio",
    name: "Creator Studio",
    tagline: "Six skills for video and podcast creators who publish consistently and grow.",
    description: "Creator Studio gives solo creators a complete writing toolkit for the full content lifecycle, from scripting and hooks through distribution and planning. Every skill is opinionated, format-aware, and built for creators who ship regularly rather than occasionally.",
    author: "Skill Me",
    category: "writing",
    tags: ["content-creator","video","social"],
    featured: false,
    verified: true,
    free: true,
    install_count: 19400,
    skill_slugs: ["youtube-script-writer","video-hook-writer","content-repurposing","show-notes-writer","thumbnail-concept","creator-content-calendar","tweet-thread-builder","linkedin-post-writer"],
  },
  {
    slug: "data-science-ml",
    name: "Data Science & ML",
    tagline: "Rigorous skills for every stage of the ML lifecycle, from EDA to production monitoring.",
    description: "This pack covers the full ML workflow with opinionated, production-tested guidance. It addresses the most common failure modes in data science: skipped EDA, dishonest evaluation, leaky features, irreproducible experiments, undocumented models, and silent drift. Each skill is self-contained and immediately applicable to real projects.",
    author: "Skill Me",
    category: "data",
    tags: ["machine-learning","data-science","mlops"],
    featured: false,
    verified: true,
    free: true,
    install_count: 19400,
    skill_slugs: ["eda-playbook","model-evaluation-report","feature-store-design","experiment-tracking","model-card-writer","data-drift-monitor","ml-feature-engineering","llm-evaluation"],
  },
  {
    slug: "educators-toolkit",
    name: "Educator's Toolkit",
    tagline: "Plan, assess, and differentiate — everything a teacher needs in one pack.",
    description: "A complete set of skills for classroom educators: design lessons, build rubrics, generate quizzes, write student feedback, map curriculum, and differentiate instruction. Each skill delivers structured, opinionated guidance that saves planning time without sacrificing pedagogical quality.",
    author: "Skill Me",
    category: "writing",
    tags: ["education","teaching","curriculum"],
    featured: false,
    verified: true,
    free: true,
    install_count: 18400,
    skill_slugs: ["lesson-plan-builder","rubric-builder","quiz-generator","student-feedback-writer","curriculum-mapper","differentiated-instruction","study-system","research-synthesis"],
  },
  {
    slug: "finance-accounting-ops",
    name: "Finance & Accounting Ops",
    tagline: "Close the books, build the forecast, and control spend with precision.",
    description: "Six skills covering the core financial operations of any growing company, from month-end close to FP&A modeling. Designed for finance teams, controllers, and operators who need structured, opinionated guidance without the consulting overhead.",
    author: "Skill Me",
    category: "business",
    tags: ["finance","accounting","fpa"],
    featured: false,
    verified: true,
    free: true,
    install_count: 11200,
    skill_slugs: ["month-end-close","financial-statement-builder","budget-vs-actual","cash-flow-forecast","fpa-model","expense-policy","unit-economics","revenue-modeling"],
  },
  {
    slug: "health-and-longevity",
    name: "Health & Longevity",
    tagline: "Evidence-informed skills for building strength, mobility, and lasting health.",
    description: "A curated collection of skills covering nutrition, strength training, lab literacy, injury prevention, longevity protocols, and daily mobility. Each skill provides structured, opinionated guidance grounded in current evidence. General wellness education only — not a substitute for professional medical advice.",
    author: "Skill Me",
    category: "personal",
    tags: ["health","fitness","longevity"],
    featured: false,
    verified: true,
    free: true,
    install_count: 18600,
    skill_slugs: ["nutrition-planner","strength-training-plan","bloodwork-explainer","injury-prehab","longevity-protocol","mobility-routine","fitness-program","sleep-optimizer"],
  },
  {
    slug: "lifecycle-marketing",
    name: "Lifecycle & Email Marketing",
    tagline: "Map journeys, activate users, and protect your sender reputation end to end.",
    description: "A complete toolkit for lifecycle and email marketers, covering journey mapping, drip sequences, win-back campaigns, behavioral segmentation, push notification copy, and deliverability. Each skill is opinionated and immediately actionable, designed to reduce guesswork and ship better campaigns faster.",
    author: "Skill Me",
    category: "writing",
    tags: ["lifecycle","email","retention"],
    featured: false,
    verified: true,
    free: true,
    install_count: 14800,
    skill_slugs: ["lifecycle-journey-map","email-drip-builder","win-back-campaign","segmentation-strategy","push-notification-copy","email-deliverability","email-newsletter-pro","churn-reduction"],
  },
  {
    slug: "performance-marketing",
    name: "Performance Marketing",
    tagline: "Audit, test, and scale paid channels with rigorous, data-driven playbooks.",
    description: "A practical toolkit for performance marketers who need to cut waste, improve conversion, and scale paid acquisition profitably. Covers the full paid marketing loop from channel auditing and creative testing through attribution, budget pacing, and audience strategy.",
    author: "Skill Me",
    category: "business",
    tags: ["marketing","paid-ads","growth"],
    featured: false,
    verified: true,
    free: true,
    install_count: 19600,
    skill_slugs: ["paid-acquisition-audit","ad-creative-testing","landing-page-cro","marketing-attribution","budget-pacing","audience-targeting","landing-page-copy","ab-test-analyzer"],
  },
  {
    slug: "personal-finance-mastery",
    name: "Personal Finance Mastery",
    tagline: "Build a solid financial foundation — budget, pay off debt, and plan for the future.",
    description: "Personal Finance Mastery brings together eight skills that cover the full personal finance lifecycle, from building a first budget to projecting retirement readiness. Each skill provides concrete, opinionated frameworks so users can take action immediately rather than getting lost in abstract advice.",
    author: "Skill Me",
    category: "personal",
    tags: ["money","personal-finance","budgeting"],
    featured: false,
    verified: true,
    free: true,
    install_count: 14800,
    skill_slugs: ["budget-builder","debt-payoff-planner","tax-optimization","retirement-projection","emergency-fund-planner","big-purchase-decision","financial-planner","investment-basics"],
  },

  // ── Phase 4 expansion packs ──
  {
    slug: "brand-visual-identity",
    name: "Brand & Visual Identity",
    tagline: "Six skills for building brands that look intentional from day one.",
    description: "A focused set of skills covering every layer of brand and visual identity work: naming, color, typography, moodboarding, logo briefing, and compositional hierarchy. Built for designers, brand strategists, and founders who need structured, opinionated guidance without guesswork.",
    author: "Skill Me",
    category: "design",
    tags: ["branding","visual-identity","design"],
    featured: false,
    verified: true,
    free: true,
    install_count: 19300,
    skill_slugs: ["logo-brief-writer","color-palette-builder","typography-system","moodboard-builder","visual-hierarchy","brand-naming","brand-guidelines","icon-system"],
  },
  {
    slug: "skill-builder-studio",
    name: "Skill Builder Studio",
    tagline: "Author, test, and curate Claude Agent Skills with confidence",
    description: "A meta-pack for engineers and prompt designers who build Claude Agent Skills. Covers the full authoring lifecycle: writing skills, crafting discoverable descriptions, testing trigger accuracy, converting prompts into skills, and curating coherent packs.",
    author: "Skill Me",
    category: "coding",
    tags: ["agent-skills","meta","authoring"],
    featured: true,
    verified: true,
    free: true,
    install_count: 14200,
    skill_slugs: ["skill-author","skill-description-writer","skill-tester","prompt-to-skill","skill-pack-curator","prompt-engineer","mcp-builder"],
  },

  // ── Phase 5 expansion packs (gap-fill: g-2026-06) ──
  {
    slug: "database-performance",
    name: "Database Performance & Administration",
    tagline: "Make slow queries fast and keep your database healthy under load.",
    description: "The DBA-grade toolkit backend engineers actually reach for: hunt N+1s, read EXPLAIN plans, advise indexes, rewrite pathological SQL, plan partitioning, tune connection pools, ship zero-downtime migrations, and debug replica lag. Built around verifiable, EXPLAIN-checkable work, not folklore.",
    author: "Skill Me",
    category: "data",
    tags: ["database","performance","postgres","sql"],
    featured: true,
    verified: true,
    free: true,
    install_count: 21800,
    skill_slugs: ["n-plus-one-hunter","explain-plan-reader","index-advisor","query-rewriter","partition-planner","connection-pool-tuner","migration-safety-checker","replication-lag-debugger","sql-query-optimizer","database-schema"],
  },
  {
    slug: "legacy-modernization",
    name: "Legacy Modernization & Migration",
    tagline: "Move old code to modern stacks without a risky big-bang rewrite.",
    description: "Brownfield work, encoded. Plan strangler-fig migrations, drive major framework and language-version upgrades, extract the business rules buried in tangled code, pin behavior with characterization tests, eliminate dead code with evidence, and decompose a monolith along real bounded-context seams.",
    author: "Skill Me",
    category: "coding",
    tags: ["legacy","migration","refactoring","modernization"],
    featured: true,
    verified: true,
    free: true,
    install_count: 16400,
    skill_slugs: ["strangler-fig-planner","framework-upgrader","language-version-migrator","business-rule-extractor","characterization-test-writer","dead-code-eliminator","monolith-decomposer","dependency-risk-audit","tdd-expert"],
  },
  {
    slug: "qa-test-automation",
    name: "QA & Test Automation",
    tagline: "Build a test suite that actually catches bugs — and stops flaking.",
    description: "Beyond unit tests and TDD: detangle flaky tests at the root, find risk-weighted coverage gaps, build clean fixtures and factories, write consumer-driven contract tests, author maintainable Playwright/Cypress E2E, design mocks without over-mocking, and use mutation testing to expose assertions that verify nothing.",
    author: "Skill Me",
    category: "coding",
    tags: ["testing","qa","automation","quality"],
    featured: false,
    verified: true,
    free: true,
    install_count: 15200,
    skill_slugs: ["flaky-test-detangler","coverage-gap-finder","test-data-builder","contract-test-writer","e2e-scenario-author","mock-stub-designer","mutation-test-runner","playwright-testing","tdd-expert"],
  },
  {
    slug: "mobile-app-engineering",
    name: "Mobile App Engineering",
    tagline: "Build and ship native and cross-platform mobile apps with Claude.",
    description: "The mobile stack the catalog was missing. Build Jetpack Compose and Flutter UIs with correct state flow, implement local-first offline sync with real conflict resolution, wire APNs/FCM push end to end, profile jank and memory, and get through App Store and Play submission without the usual rejections.",
    author: "Skill Me",
    category: "coding",
    tags: ["mobile","ios","android","cross-platform"],
    featured: true,
    verified: true,
    free: true,
    install_count: 14600,
    skill_slugs: ["swift-ui","react-native-pro","jetpack-compose-builder","flutter-widget-architect","mobile-offline-sync","push-notification-wirer","mobile-perf-profiler","app-store-release-prep"],
  },
  {
    slug: "api-integration-engineering",
    name: "API & Integration Engineering",
    tagline: "Ship integrations that survive retries, rate limits, and breaking changes.",
    description: "The resilience layer for backend engineers building and consuming APIs: enforce idempotency, harden webhook receivers, back off correctly under rate limits, add circuit breakers and bulkheads, design date-pinned versioning and deprecation, build cursor pagination and delta sync, and generate typed resilient clients from OpenAPI.",
    author: "Skill Me",
    category: "coding",
    tags: ["api","integration","webhooks","reliability"],
    featured: false,
    verified: true,
    free: true,
    install_count: 17300,
    skill_slugs: ["idempotency-enforcer","webhook-receiver-hardener","rate-limit-handler","circuit-breaker-builder","api-versioning-strategist","pagination-and-sync-engineer","api-client-generator","api-design","oauth-flow"],
  },
  {
    slug: "seo-organic-growth",
    name: "SEO & Organic Growth Engine",
    tagline: "Turn a keyword into ranked, AI-search-ready content — end to end.",
    description: "The organic-search workflow as skills: cluster keywords into a pillar/cluster architecture, classify search intent to the right page type, close SERP coverage gaps, write pixel-perfect titles and metas, map internal links for topical authority, engineer citable answer blocks for AI search (AEO/GEO), and refresh decaying content.",
    author: "Skill Me",
    category: "business",
    tags: ["seo","organic-growth","content","aeo"],
    featured: true,
    verified: true,
    free: true,
    install_count: 20400,
    skill_slugs: ["keyword-cluster-builder","search-intent-classifier","serp-gap-analyzer","meta-title-optimizer","internal-linking-mapper","aeo-answer-blockifier","content-refresh-auditor","seo-optimizer","content-brief"],
  },
  {
    slug: "social-media-studio",
    name: "Social Media Manager Studio",
    tagline: "A month of on-brand posts, repurposed everywhere, in an afternoon.",
    description: "The channel-native cadence the catalog lacked. Plan a multi-platform content calendar, write captions and scroll-stopping hooks per platform, reformat one idea across LinkedIn/X/Instagram/TikTok, build tiered hashtag and keyword sets, draft graceful comment and DM replies at scale, and script swipe-through carousels.",
    author: "Skill Me",
    category: "writing",
    tags: ["social-media","content","marketing","community"],
    featured: false,
    verified: true,
    free: true,
    install_count: 23600,
    skill_slugs: ["social-content-calendar","social-caption-writer","social-hook-generator","cross-platform-reformatter","hashtag-strategist","engagement-reply-drafter","carousel-scripter","linkedin-post-writer","tweet-thread-builder"],
  },
  {
    slug: "ecommerce-dtc-ops",
    name: "E-commerce & DTC Operations",
    tagline: "From product page to abandoned-cart flow — copy that converts.",
    description: "The DTC operator's copy stack: benefit-led product descriptions, Amazon listings within the platform's rules, variant copy that dodges duplicate-content penalties, review-mined FAQs, commercial-intent category pages, margin-protecting cart-recovery sequences, and honest comparison pages that win 'vs' searches.",
    author: "Skill Me",
    category: "business",
    tags: ["ecommerce","dtc","conversion","copywriting"],
    featured: false,
    verified: true,
    free: true,
    install_count: 18900,
    skill_slugs: ["product-description-writer","amazon-listing-optimizer","variant-copy-scaler","review-to-faq-builder","category-page-copywriter","abandoned-cart-sequence","comparison-page-builder","landing-page-cro","email-drip-builder"],
  },
  {
    slug: "people-ops-recruiting",
    name: "People Ops & Recruiting Toolkit",
    tagline: "Hire, onboard, and run a team fairly — without a full HR department.",
    description: "The employer side of hiring, built fair by default. Write inclusive job descriptions and scrub them for bias, turn JDs into weighted scorecards and structured STAR question kits, personalize candidate outreach, draft careful offers and rejections, build 30/60/90 onboarding plans, and synthesize interview debriefs. Every skill keeps a human as decision-maker with explicit fairness bounds.",
    author: "Skill Me",
    category: "business",
    tags: ["hiring","recruiting","people-ops","management"],
    featured: false,
    verified: true,
    free: true,
    install_count: 13100,
    skill_slugs: ["job-description-writer","jd-bias-scrubber","screening-rubric-builder","interview-question-kit","candidate-outreach-personalizer","offer-rejection-writer","onboarding-plan-builder","interview-debrief-synthesizer","hiring-scorecard","feedback-writer"],
  },
  {
    slug: "gym-growth-engine",
    name: "Gym Growth Engine",
    tagline: "The operator stack to fill, sell, and scale a gym.",
    description: "The operator's stack for running a gym on the offer, lead-gen, sales, and money-model frameworks behind Gym Launch and Acquisition.com. Model unit economics and Client-Financed Acquisition, build a Grand Slam Offer and premium pricing, fill the gym with a transformation challenge and Meta ads, close with the CLOSER consult and beat objections, kill churn, drive referrals, and run it all on a KPI scoreboard. Every skill operationalizes the method with runnable calculators and ready templates.",
    author: "Skill Me",
    category: "business",
    tags: ["gym","fitness","sales","unit-economics"],
    featured: false,
    verified: true,
    free: true,
    install_count: 9600,
    repo_url: "https://github.com/aouellets/gym-growth-engine",
    skill_slugs: ["gym-money-model","grand-slam-offer-builder","gym-pricing-and-guarantees","core-four-lead-engine","gym-transformation-challenge","gym-meta-ads-funnel","closer-sales-script","objection-handling-and-speed-to-lead","retention-and-churn-killer","referral-and-affiliate-system","kpi-scoreboard-and-cadence","hiring-a-players-and-sops"],
  },
  {
    slug: "founder-fundraising-os",
    name: "Founder Fundraising OS",
    tagline: "Everything a founder needs to raise a round — from deciding the stage to wired funds.",
    description: "The complete operating system for raising venture capital, end to end. Decide your stage, amount, and valuation; run an honest readiness audit; model your cap table and dilution; build the pitch deck and narrative; size the market and financials; assemble a staged data room; shape the team story and key hires. Then run the raise like a sales process: target the right VCs and angels with warm paths, manage the pipeline to manufacture momentum, drill the pitch and the hard Q&A, pass diligence, negotiate the term sheet, choose SAFE vs priced, and drive the close to cash. Every skill is operator-grade with concrete checklists and deliverables.",
    author: "Skill Me",
    category: "business",
    tags: ["fundraising","startup","venture-capital","founder"],
    featured: true,
    verified: true,
    free: true,
    install_count: 0,
    repo_url: "https://github.com/aouellets/founder-fundraising-os",
    skill_slugs: [
      "fundraising-stage-selector","fundraise-readiness-audit","cap-table-manager",
      "market-sizing","financial-planner",
      "fundraising-narrative","pitch-deck-builder","data-room-builder",
      "fundraise-team-hiring",
      "investor-targeting","vc-pitch-email","investor-pipeline-crm","investor-update-writer",
      "pitch-practice-coach","series-a-readiness","due-diligence-checklist",
      "term-sheet-explainer","safe-vs-priced-round","term-sheet-negotiation","fundraise-closing-mechanics",
    ],
  },
  {
    slug: "remotion-video-production",
    name: "Remotion Video Production",
    tagline: "Turn natural language briefs into rendered MP4s using Claude Code and Remotion — covers project setup, composition generation, and the render/iterate loop.",
    description: "Produce software product demos, feature-announcement videos, and marketing animations without a video editor or motion-design background. Three skills that work in sequence — Remotion Setup scaffolds a project wired for Claude Code Agent Skills, Remotion Compose turns a natural-language brief into a complete React/TypeScript composition, and Remotion Render handles export plus the feedback-and-re-render loop — and each is independently useful once a project is underway. Built for developers, product teams, and solo founders who want to describe a video and get a rendered MP4 back.",
    author: "Skill Me",
    category: "coding",
    tags: ["remotion", "video", "react", "claude-code"],
    featured: true,
    verified: true,
    free: true,
    install_count: 0,
    skill_slugs: [
      "remotion-setup", "remotion-compose", "remotion-render",
    ],
  },
  {
    slug: "resume-toolkit",
    name: "Resume Toolkit",
    tagline: "Write a resume from scratch or critique the one you have — ATS-optimized, seniority-aware, delivered as .docx.",
    description: "A two-skill loop for getting a resume right. Resume Writer runs a short elicitation, then drafts a complete ATS-optimized resume — tailored summary, STAR-format action-verb bullets quantified wherever possible, clean standard sections — and exports a .docx. Resume Reviewer critiques an existing resume against a scored rubric (impact, ATS readiness, clarity, format/length), returns a prioritized fix list, rewrites the weakest bullets, and runs a keyword gap analysis against a target job description — also as a .docx. The two hand off to each other: review, then rebuild clean. Both are seniority-aware (IC vs manager vs executive), carry a strong action-verb library, follow ATS best practices throughout, and give honest, direct feedback.",
    author: "Skill Me",
    category: "personal",
    tags: ["resume", "career", "job-search", "ats"],
    featured: true,
    verified: true,
    free: true,
    install_count: 0,
    repo_url: "https://github.com/aouellets/resume-toolkit",
    skill_slugs: [
      "resume-writer", "resume-reviewer",
    ],
  },

]
