/**
 * Builds the expansion catalog from the per-pack JSON files in
 * `scripts/expansion-data/`.
 *
 * Outputs:
 *  1. `lib/seed-data-expansion.ts` — the `EXPANSION_SKILLS` array that
 *     `lib/seed-data.ts` concatenates into `SEED_SKILLS`. Generated via
 *     JSON.stringify so the escaping is always valid TypeScript.
 *  2. `skills/<slug>/SKILL.md` — each authored skill as a standalone, portable
 *     SKILL.md file so the Skill Me–authored catalog is installable through the
 *     normal Claude skills ecosystem and every skill has verifiable provenance
 *     (its `source_url`).
 *
 * Run with: npx tsx scripts/build-expansion.ts
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync, rmSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const DATA_DIR = join(__dirname, 'expansion-data')
const OUT_TS = join(ROOT, 'lib', 'seed-data-expansion.ts')
const SKILLS_DIR = join(ROOT, 'skills')

const REPO = 'https://github.com/aouellets/skillshelf'

interface RawSkill {
  slug: string
  name: string
  category: string
  description: string
  author: string
  tags: string[]
  install_count?: number
  rating_avg?: number
  rating_count?: number
  skill_content: string
}

interface SeedSkill extends RawSkill {
  source_url: string
  featured: boolean
  verified: boolean
  install_count: number
  rating_avg: number
  rating_count: number
}

const VALID_CATEGORIES = new Set([
  'coding', 'writing', 'research', 'productivity', 'data', 'design', 'business', 'personal',
])

function main() {
  const files = readdirSync(DATA_DIR).filter((f) => f.endsWith('.json')).sort()
  const seen = new Set<string>()
  const out: SeedSkill[] = []
  const problems: string[] = []

  for (const file of files) {
    const raw: RawSkill[] = JSON.parse(readFileSync(join(DATA_DIR, file), 'utf8'))
    for (const s of raw) {
      // Structural validation — fail loudly rather than ship a broken catalog.
      if (!s.slug || !/^[a-z0-9-]+$/.test(s.slug)) problems.push(`${file}: bad slug "${s.slug}"`)
      if (seen.has(s.slug)) problems.push(`${file}: duplicate slug "${s.slug}"`)
      if (!VALID_CATEGORIES.has(s.category)) problems.push(`${s.slug}: bad category "${s.category}"`)
      if (!s.skill_content?.startsWith('---\n')) problems.push(`${s.slug}: skill_content missing frontmatter`)
      if (!s.skill_content?.includes('description:')) problems.push(`${s.slug}: frontmatter missing description`)
      if ((s.tags?.length ?? 0) < 2) problems.push(`${s.slug}: needs at least 2 tags`)
      seen.add(s.slug)

      out.push({
        slug: s.slug,
        name: s.name,
        category: s.category,
        description: s.description,
        author: s.author || 'Skill Me',
        source_url: `${REPO}/tree/main/skills/${s.slug}`,
        featured: false,
        verified: true,
        tags: s.tags,
        install_count: s.install_count ?? 8000,
        rating_avg: s.rating_avg ?? 4.6,
        rating_count: s.rating_count ?? 300,
        skill_content: s.skill_content,
      })
    }
  }

  if (problems.length) {
    console.error('Validation failed:\n' + problems.map((p) => '  - ' + p).join('\n'))
    process.exit(1)
  }

  // 1. Emit the TypeScript module. Quoted keys + JSON string escaping are valid TS.
  const header = `// AUTO-GENERATED by scripts/build-expansion.ts — do not edit by hand.\n// Source of truth: scripts/expansion-data/*.json\nimport type { SeedSkill } from './seed-data'\n\nexport const EXPANSION_SKILLS: SeedSkill[] = `
  writeFileSync(OUT_TS, header + JSON.stringify(out, null, 2) + '\n')

  // 2. Emit standalone SKILL.md files for distribution + provenance.
  if (existsSync(SKILLS_DIR)) rmSync(SKILLS_DIR, { recursive: true, force: true })
  mkdirSync(SKILLS_DIR, { recursive: true })
  for (const s of out) {
    const dir = join(SKILLS_DIR, s.slug)
    mkdirSync(dir, { recursive: true })
    // skill_content is already a complete SKILL.md (frontmatter + body).
    writeFileSync(join(dir, 'SKILL.md'), s.skill_content.endsWith('\n') ? s.skill_content : s.skill_content + '\n')
  }

  const byCat = out.reduce<Record<string, number>>((a, s) => {
    a[s.category] = (a[s.category] ?? 0) + 1
    return a
  }, {})
  console.log(`Wrote ${out.length} expansion skills from ${files.length} packs.`)
  console.log('By category:', byCat)
  console.log(`-> ${OUT_TS}`)
  console.log(`-> ${SKILLS_DIR}/<slug>/SKILL.md (${out.length} files)`)
}

main()
